services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic_apiv2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: sh -c "poetry run python -m api.main"

  
